#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LinearRecycler.Resource", IsApplication=true)]

namespace LinearRecycler
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Com.Syncfusion.Gauges.Resource.Dimension.pading_bottom = global::LinearRecycler.Resource.Dimension.pading_bottom;
			global::Com.Syncfusion.Gauges.Resource.Dimension.pading_top = global::LinearRecycler.Resource.Dimension.pading_top;
			global::Com.Syncfusion.Gauges.Resource.Id.eightsegment = global::LinearRecycler.Resource.Id.eightsegment;
			global::Com.Syncfusion.Gauges.Resource.Id.fourteensegment = global::LinearRecycler.Resource.Id.fourteensegment;
			global::Com.Syncfusion.Gauges.Resource.Id.rootLayout = global::LinearRecycler.Resource.Id.rootLayout;
			global::Com.Syncfusion.Gauges.Resource.Id.sevensegment = global::LinearRecycler.Resource.Id.sevensegment;
			global::Com.Syncfusion.Gauges.Resource.Id.sixteensegment = global::LinearRecycler.Resource.Id.sixteensegment;
			global::Com.Syncfusion.Gauges.Resource.Layout.circulargauge_layout = global::LinearRecycler.Resource.Layout.circulargauge_layout;
			global::Com.Syncfusion.Gauges.Resource.Layout.digitalgauge_layout = global::LinearRecycler.Resource.Layout.digitalgauge_layout;
			global::Com.Syncfusion.Gauges.Resource.String.ApplicationName = global::LinearRecycler.Resource.String.ApplicationName;
			global::Com.Syncfusion.Gauges.Resource.String.Hello = global::LinearRecycler.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f030000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int item_touch_helper_swipe_escape_velocity = 2130903042;
			
			// aapt resource value: 0x7f030004
			public const int pading_bottom = 2130903044;
			
			// aapt resource value: 0x7f030003
			public const int pading_top = 2130903043;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040003
			public const int eightsegment = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int fourteensegment = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int fragment_container = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int gauge1 = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_previous_elevation = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int linear = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int next = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int prev = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int recyclerView = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int rootLayout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int sevensegment = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int sixteensegment = 2130968581;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int circulargauge_layout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int digitalgauge_layout = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int gauge = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Main = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int MyFragment = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int row = 2130837509;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
